### ISSUE TITLE
Implement CLI

### ISSUE THREAD

**Issue by samuelflock** [samuelflock/TabIt#10]
As a developer and user, I want to interact with the program through CLI, so that I can have some kind of user input (especially for development)

## Definition of Done
- [x] Program allows user input to select: model and source
- [x] Program provides feedback about user's actions (help, success, failure, etc.)

## Tasks
- [x] Create a basic CLI to listen for user input that parses model and source with feedback
