### ISSUE TITLE
Convert MP3 into Guitar Tab

### ISSUE THREAD

**Issue by samuelflock** [samuelflock/TabIt#18]
As a user, I want to have existing mp3 files converted to Guitar Tabs, so that I can utilize the full functionality of the program

## Definition of Done
- [ ] Files are converted to Tabs immediately after downloading them
- [ ] Tabs are saved to a TBD folder in a TBD format

## Tasks
- [x] Find Python Library that takes in mp3 and returns tabs
- [ ] Implement the same Library and save tabs
