### ISSUE TITLE
Implement YouTube Download

### ISSUE THREAD

**Issue by samuelflock** [samuelflock/TabIt#9]
As a user, I want to enter a link for an audio source, so that I can more easily input a song source

## Definition of Done
- [ ] User is able to provide a link to YouTube
- [ ] The link's source is formatted into .mp3 and saved to music folder
- [ ] New file in music folder is ran through Demucs

## Tasks
- [x] Find and Install a YouTube Download library
- [ ] Allow argument in CLI for link and download using library
- [ ] Convert YouTube Download output into .mp3 and save to music folder
- [ ] Run new file in music folder through Demucs
